---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  pre_tasks:
    - name: (CONVERGE - PREPARE) Install dependencies
      ansible.builtin.apt:
        name:
          - gnupg
          - python3-all
          - python3-pip
        update_cache: true
        state: present
  roles:
    - docker
