# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus      = 1
    libvirt.cpu_mode  = 'host-passthrough'
    libvirt.memory    = 1024
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose         = "v"
    ansible.playbook        = "../../run.yml"
  end
end