---
- name: (DEBIAN) Docker repo config in Debian hosts
  when: ansible_distribution == 'Debian'
  ansible.builtin.include_tasks:
    file: debian.yml

- name: (PACKAGES) Install Docker
  ansible.builtin.package:
    name: "{{ docker_pkgs }}"
    state: present

- name: (PYLIBS) Install Docker Python libs
  ansible.builtin.package:
    name: "{{ docker_python_libs }}"
    state: present

- name: (PYLIBS) Install Docker Python packages (Workaround for Docker modules)
  ansible.builtin.pip:
    name: "{{ docker_python_pkgs }}"
    extra_args: '--break-system-packages'
    state: present

- name: (OPUSER) Create user for Docker ops (without password)
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: "{{ docker_group }}"
    shell: /bin/bash
    password: '!'     # Disabled pass by default
    append: true
    state: present
