---
- name: (PREPARE - USERGROUP) Get user info
  ansible.builtin.getent:
    database: passwd
    key: "{{ pihole_user }}"

- name: (PREPARE - USERGROUP) Get group info
  ansible.builtin.getent:
    database: group
    key: "{{ pihole_group }}"

- name: (PREPARE - USERGROUP) Set UID as fact
  ansible.builtin.set_fact:
    pihole_uid: "{{ ansible_facts['getent_passwd'][pihole_user][1] }}"

- name: (PREPARE - USERGROUP) Set GID as fact
  ansible.builtin.set_fact:
    pihole_gid: "{{ ansible_facts['getent_group'][pihole_group][1] }}"
